
- name: install the latest version of wget
  package:
    name: wget
    state: latest

- name: Set up persistent etcd data directory
  file:
    path:  /var/lib/{{ installation_dir }}
    state: directory
    owner: root
    group: root
    mode:  0775

- name:  Fetch new etcd
  get_url:
    url: https://github.com/coreos/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
    dest: /tmp/

- name: Unarchive new etcd
  unarchive:
    src: /tmp/etcd-v{{ etcd_version }}-linux-amd64.tar.gz 
    dest: /tmp
    remote_src: yes

- name: Install new etcd
  shell: |
    cd /tmp/etcd-v{{ etcd_version }}-linux-amd64
    mv etcd /usr/local/sbin/etcd3
    mv etcdctl /usr/local/sbin/etcdctl
    chmod 755 /usr/local/sbin/etcd3 /usr/local/sbin/etcdctl

- name: Put systemd service file
  tags: systemd
  template:
    src: etcd3.service.j2
    dest: /etc/systemd/system/etcd3.service
    owner: root
    group: root
    mode: 0644

- name: Reload and start the services
  shell: |
    systemctl daemon-reload
    systemctl enable etcd3.service
    systemctl start  etcd3.service

- name: Put example file, how to restore from backup
  template:
    src: etcd-restore-command
    dest: /tmp/etcd-restore-example
    owner: root
    group: root
    mode: 0644

- name: Setup a defrag rule
  template:
    src: defrag-etcd.sh
    dest: /usr/local/sbin/defrag-etcd
    owner: root
    group: root
    mode: 0755
