---
- name: Install etcd3
  hosts: nodes
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Generate certs
      import_role:
        name: tls_cert
      when: tls.enabled

    - name: Install Etcd
      import_role:
        name: install_etcd
